### ISSUE TITLE
Having issues with loading session using sqlalchemy backend

### ISSUE THREAD

**Issue by markosski** [pallets-eco/flask-session#26]
I noticed there was a fix added for Python 3 to the way session string is handled but I'm still having problems.
`data = self.serializer.loads(want_bytes(val))` When this line executes in open_session I'm still not getting my session back. I poked around I noticed pickle is raising exception of type `_pickle.UnpicklingError` with no message to it.

Python 3.4.0
SQLAlchemy 0.9.8 + MySQL 5.5
Flask 0.10.1

**Comment by martez81** [comment]
In order to make it work I had to do the following changes.
- in `class Session` data column was changed to `data = self.db.Column(self.db.BLOB)`
- in `open_session` method unserializing changed to `data = self.serializer.loads(val)` 
- in `open_session` when testing for expiration added test for existence of vlaue `if saved_session and saved_session.expiry != None and saved_session.expiry <= datetime.utcnow():` This is because upon calling `session.clear()` in application `self.get_expiration_time(app, session)` returns `None` and expiry will be set to Null in database.

**Comment by mcrowson** [comment]
This issue was moved to mcrowson/flask-session#8

**Comment by Lxstr** [comment]
Fixed post 0.6.0
