### ISSUE TITLE
session.clear() not work correctly with mongodb

### ISSUE THREAD

**Issue by efazati** [pallets-eco/flask-session#64]
I used `session.clear() ` with mongodb back-end
and delete cookie from client correctly but when user save cookie separately and send to server. I have session with this cookie.
How can solve this problem?

**Comment by vanastassiou** [comment]
I'm not sure whether this is the same problem as the one I just worked around (Redis back-end). My problem looked like this:

1. Logged-in user initiates a query
1. User logs out before query completes
1. New user logs in using same browser
1. After new user successfully authenticates, old user's session is restored

I found that this was because Flask calls `save_session()` at the end of every request, which re-saves the requesting user's session to the back end. My work-around was as follows:

1. In my server's `login()` function, add `is_login: True` attribute to the session immediately after the server returns a response containing the session
1. Update `save_session()` to check for `is_login` early and:
    * Immediately save session to back end if `True` and remove the `is_login` attribute
    * Check for a back-end session matching the request and return if none
